source 'https://rubygems.org'

group(:test) do
  gem 'capybara', '3.31.0'
  gem 'capybara-screenshot'
  gem 'ffi'
  gem 'rake'
  gem 'rspec'
  gem 'rspec-steps'
  gem 'selenium-webdriver', '3.142.7'
  gem 'single_test'
  gem 'true_automation'
  # gem 'true_automation', git: 'https://github.com/educator-io/trueautomation-libraries', branch: 'master', glob: 'ruby/true_automation/true_automation.gemspec'
end
